apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: blog
type: Opaque
stringData:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wpuser
  MYSQL_PASSWORD: "ChangeMe-Temp123!"
  MYSQL_ROOT_PASSWORD: "RootTemp-ChangeMe!"
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: blog
type: Opaque
stringData:
  WORDPRESS_DB_HOST: mariadb.blog.svc.cluster.local
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wpuser
  WORDPRESS_DB_PASSWORD: "ChangeMe-Temp123!"
