apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: wordpress-probe
  namespace: monitoring
spec:
  module: http_2xx
  prober:
    url: bb-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
      - https://web.etna.student/
